import React from "react";

const Insights = () => {
  return (
    <section className="insights">
      <div className="insights-container">
        {/* Top badge */}
        <div className="badge">✦ Blog</div>

        {/* Heading */}
        <h2 className="insights-title">
          Latest <span>Insights</span>
        </h2>
        <p className="insights-subtitle">
          Explore my thoughts on Startups, technology, and Student Life in
          Germany.
        </p>

        {/* Cards */}
        <div className="insights-grid">
          {/* Card 1 */}
          <div className="insight-card">
            <div className="card-meta">
              <span>📅 October 2, 2025</span>
              <span>⏱ 10 min read</span>
            </div>

            <h3>
              From Script to Screen in Hours: How AI is Turning Anyone into a
              Content Creator
            </h3>

            <p>
              Remember when making a professional ad required a $50k budget and
              a full production crew? Yeah, those days are pretty much over.
              Let's talk about how AI is...
            </p>

            <div className="card-footer">
              <span className="ai-tag">👤 Generated by AI</span>
              <a href="/">Read more →</a>
            </div>

            <div className="tags">
              <span>AI</span>
              <span>Content Creation</span>
              <span>Advertising</span>
            </div>
          </div>

          {/* Card 2 */}
          <div className="insight-card">
            <div className="card-meta">
              <span>📅 September 28, 2025</span>
              <span>⏱ 6 min read</span>
            </div>

            <h3>
              The Vibe of Coding with AI: How Conversational AI is Reshaping
              Development and Work
            </h3>

            <p>
              Ever wondered how developers are suddenly shipping features 3x
              faster? Or why call centers are becoming obsolete? Let's dive into
              the real story of AI...
            </p>

            <div className="card-footer">
              <span className="ai-tag">👤 Generated by AI</span>
              <a href="/">Read more →</a>
            </div>

            <div className="tags">
              <span>AI</span>
              <span>Development</span>
              <span>Productivity</span>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Insights;
